function drawFieldVectors(medial_axis_smoothed,mag_vectors_st,mag_off,mag_on)
drawVector3d(medial_axis_smoothed(:,mag_off(1:4:end))',...
    0.4*mag_vectors_st(:,mag_off(1:4:end))','c');
drawVector3d(medial_axis_smoothed(:,mag_off)',...
    0.1*mag_vectors_st(:,mag_off)', 'c', 'ShowArrowHead','off');
drawVector3d(medial_axis_smoothed(:,mag_on(1:4:end))',...
    0.6*mag_vectors_st(:,mag_on(1:4:end))', 'Color', [0.9 0.7 0.125]);
drawVector3d(medial_axis_smoothed(:,mag_on)',...
    0.2*mag_vectors_st(:,mag_on)', 'Color', [0.9 0.7 0.125], 'ShowArrowHead','off');
end