function trial_coil_temps = importCoilTemps(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PHANTOMGMEA1TRIAL21 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  PHANTOMGMEA1TRIAL21 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  phantomgmea1trial21 = importfile("C:\Users\riojaske\Documents\magsteer\Magnetic-Guidance\data\phantom\Coil Temps\phantom_g_mea1_trial2_1.25_coiltemps.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Dec-2019 08:09:30

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "fieldx", "fieldy", "fieldz"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
phantomgmea1trial21 = readtable(filename, opts);

%% Convert to output type
coil_temps = table2array(phantomgmea1trial21);
trial_coil_temps.time = coil_temps(:,1)*10^-9 - coil_temps(1,1)*10^-9;
trial_coil_temps.Tx = coil_temps(:,2) - coil_temps(1,2);
trial_coil_temps.Ty = coil_temps(:,3) - coil_temps(1,3);
trial_coil_temps.Tz = coil_temps(:,4) - coil_temps(1,4);

end